services:

  mongodb:
    image: 'mongo:8.0.3'
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: studentdb
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth
    networks:
      nyos-net:

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://admin:mongo@mongo:27017/studentdb?authSource=admin
    networks:
      nyos-net:

  keycloak:
    image: 'keycloak/keycloak:26.0.5'
    container_name: keycloak
    ports:
      - 9090:8080
    restart: always
    depends_on:
      - keycloakDB
    command:
      - start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakDB:5432/keycloakDB
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HTTP_RELATIVE_PATH: /auth
    networks:
      nyos-net:

  keycloakDB:
    image: 'postgres:17.1-alpine'
    container_name: keycloakDB
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloakDB
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    networks:
      nyos-net:

volumes:
  mongodb_data:
    driver: local
  keycloak_db:
    driver: local
networks:
  nyos-net: