server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.data.mongodb.database}?authSource=admin
      username: admin
      password: mongo
      database: studentdb


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

keycloak:
  url: http://localhost:9090/auth
  realm: nyos
  client-id: administration-client
  client-secret: oJIeP6uXtECc5t0xnBk1BJQDfqZnS1tJ
  username: nyos
  password: admin
  grant-type: password